### PR TITLE
Credential bastion

### PR DESCRIPTION
**Pull request by ntwkninja**
- credentials bastion to provision an EKS cluster
- credentials bastion to create EFS filesystem
- adds a conditional flag (default false) for the privileged IAM policy to be enabled on the bastion
  - supports reusability of the module in different capacities without over-permissioning those resources

### CODE REVIEW

**Comment by ntwkninja** [comment]
closes #248

**Comment by brianrexrode** [comment]
Is this PR meant to address the issues with the `<cluster>-aws-efs-csi-driver-sa-irsa` policy that seems to be blocking the ability to create EFS access points?

**Comment by ntwkninja** [comment]
> Is this PR meant to address the issues with the `<cluster>-aws-efs-csi-driver-sa-irsa` policy that seems to be blocking the ability to create EFS access points?

yes... thank you for reminding me. Updated PR description and issue to capture that as well

**Review by brianrexrode — APPROVED** [review]
LGTM

**Pull request merged**
