### PR TITLE
chore(main): release 0.0.9

### PR DESCRIPTION
**Pull request by RothAndrew**
:robot: I have created a release *beep* *boop*
---

### Features

* update eks module for blueprints v5 migration ([#337](https://github.com/defenseunicorns/delivery-aws-iac/issues/337)) ([2b7e7d5](https://github.com/defenseunicorns/delivery-aws-iac/commit/2b7e7d5f136f6eaa5f1fa74ff0318a26a02eefdb))

### Miscellaneous Chores

* **ci:** Add support for using the merge queue, refactor workflow file names, and add more docs to the workflow files ([#340](https://github.com/defenseunicorns/delivery-aws-iac/issues/340)) ([410ee6c](https://github.com/defenseunicorns/delivery-aws-iac/commit/410ee6ca4c1ba659cfce3b423b64d75793d0a1e5))
* **ci:** Fix typo in merge_group test jobs ([#342](https://github.com/defenseunicorns/delivery-aws-iac/issues/342)) ([cc15c5c](https://github.com/defenseunicorns/delivery-aws-iac/commit/cc15c5c9e85df42b44b3b8797079644bb4118386))

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by zack-is-cool — APPROVED** [review]
LGTM

**Review by zack-is-cool — APPROVED** [review]
LGTM

**Comment by RothAndrew** [comment]
:robot: Release is at https://github.com/defenseunicorns/delivery-aws-iac/releases/tag/v0.0.9 :sunflower:

**Pull request merged**
