### PR TITLE
Appease tfsec by excluding a bunch of checks

### PR DESCRIPTION
**Pull request by kirankt**
I have disabled a bunch of checks that made tfsec happy, but we will need to revisit some of these, especially

- Ingress all from all public IPs
- All ports allowed, etc

### CODE REVIEW

**Comment by ntwkninja** [comment]
Hey @kirankt, we switched over to checkov some time ago so there shouldn't be a tfsec pipeline failure. Had a brief discussion with @brianrexrode this past week and agreed that we should not skip any checks until it's been determined that the check is acceptable to skip (i.e. most of these items in the checks are things that need to be addressed).

**Comment by ntwkninja** [comment]
> > Hey @kirankt, we switched over to checkov some time ago so there shouldn't be a tfsec pipeline failure. Had a brief discussion with @brianrexrode this past week and agreed that we should not skip any checks until it's been determined that the check is acceptable to skip (i.e. most of these items in the checks are things that need to be addressed).
> 
> So, does this mean we won't be needing TFsec? Should we close #42 ?

Was just looking over that issue and it looks like @RothAndrew was planning to add it in later, which I now understand is the issue you grabbed.

Genuine question, is adding the pre-commit for tfsec but setting it to skip all the findings globally useful?

**Comment by RothAndrew** [comment]
I'm on mobile so haven't looked at the actual changes yet. If the PR is ignoring ALL rules then I agree it's not a valuable change.

I do believe in the value of using more than 1 tool since they will tend to report on different things. If we can enable a few rules without a huge lift that's valuable, and we can enable more rules incrementally.

**Comment by RothAndrew** [comment]
Closing this as stale but not deleting the branch in case we want it back.

**Pull request closed without merging**
