### PR TITLE
Add "Secure Mode" to the complete example

### LINKED ISSUE #101: Add "secure mode" to the complete example
Now that the `complete` example exists and is tested in a CI pipeline, we need to expand on it. Right now it has a setup for an "insecure mode" which does managed nodegroups, default tenancy, and turns on the public endpoint for the eks cluster. We need to add a "secure mode" which does self-managed nodegroups, dedicated tenancy, and turns off the public endpoint for the eks cluster.

Acceptance Criteria:
* Complete example has "secure mode" which is accomplished via `terraform apply -var-file=fixtures.common.tfvars -var-file=fixtures.secure.tfvars`
* Complete example "secure mode" is on par with the existing `complete-self-managed-nodegroup` example
* Secure mode uses self-managed nodegroups, dedicated instance tenancy, and turns off the eks cluster public endpoint
* Automated test for "secure mode" exists and is passing
* Documentation has been updated to give instructions on how to deploy secure mode
* `complete-self-managed-nodegroup` example has been deleted

Notes:
* Turning off the public endpoint for the eks cluster adds difficulty to this. If it is off connections to the cluster have to be tunneled through the bastion host. Two methods have been discussed around doing this:
	* Starting out with the public endpoint turned on, running terraform apply on everything, then switching it to off and running terraform apply again
	* Running terraform apply with `-target` to target specifically the vpc and the bastion, then use sshuttle to tunnel through the bastion and run `terraform apply` again

### PR DESCRIPTION
**Pull request by RothAndrew**
Closes #101

### CODE REVIEW

**Review by wirewc — DISMISSED** [review]

**Review by ntwkninja — DISMISSED** [review]
lg2m

**Comment by RothAndrew** [comment]
Getting an error on the secure mode test:

image

But it passes locally. At first I thought it might be because of the differences between using managed and self-managed node groups. Currently testing in #116.

But now because it passes locally I'm wondering whether it is due to the difference in the type of auth being used. Locally I'm using my own AWS creds, but in the pipeline it uses an OIDC provider wired up with GitHub, so it isn't a "user" applying the resource, rather it is an assumed role doing it.

I'm wondering if implementing #105 and automatically adding the role that is currently being used will fix the issue.

What's weird is, this issue is not seen in the "insecure mode" of the complete example. I'm guessing because insecure mode uses managed nodegroups, which means we don't actually create the aws-auth configmap, amazon does

**Comment by RothAndrew** [comment]
Another difference that I want to check out is that locally I'm only running one of the tests 

```
make test-complete-secure
```

But in the pipeline both tests are running in parallel

```
make test
```

**Comment by RothAndrew** [comment]
Issue has most likely been narrowed down to a race condition with the EKS cluster. Terraform was trying to use the Kubernetes Provider / Helm Provider / Kubectl Provider to deploy stuff to the cluster before it was ready.

To resolve I switched from 2 `terraform apply` runs to 3 runs: (1) `terraform apply -target=module.vpc -target=module.bastion` (2) `terraform apply -target=module.vpc -target=module.bastion -target=module.eks` (via sshuttle) (3) `terraform apply` (via sshuttle)

I also added a 30 second wait between step 2 and step 3. Doing this gives the cluster enough time to be ready to accept deployments when Terraform tries to do them.

**Comment by RothAndrew** [comment]
Currently blocked by https://github.com/defenseunicorns/iac/pull/121

**Review by zack-is-cool — APPROVED** [review]
LGTM

**Review by ntwkninja — APPROVED** [review]
Lgtm

**Pull request merged**
