### PR TITLE
Externalize logging bucket and KMS key

### LINKED ISSUE #125: Misconfigured bucket logging in s3-irsa module
```
resource "aws_s3_bucket_logging" "logging" {
  bucket = module.s3_bucket.s3_bucket_id

  target_bucket = module.s3_bucket.s3_bucket_id
  target_prefix = "log/"
}
```

because `bucket` and `target_bucket` is the same bucket, this will create an infinite loop and cost a lot of money.

Ref: https://repost.aws/knowledge-center/s3-server-access-logs-same-bucket

### LINKED ISSUE #152: Race condition causing flaky E2E testing pipeline
image

### PR DESCRIPTION
**Pull request by RothAndrew**
* Move the logging bucket to the root module, and use the same logging bucket for all access logs.
* Move the KMS key to the root module, and use the same KMS key for all encryption needs
* Delete a bunch of unused inputs in the Bastion module
* Misc formatting fixes

Closes #125
Closes #152

### CODE REVIEW

**Review by brianrexrode — COMMENTED** [review]
recommend renaming access_logging.tf to access-logging.tf for consistency

**Comment by RothAndrew** [comment]
Sure, no sweat. Anything else?

**Review by brianrexrode — APPROVED** [review]
👍

**Pull request merged**
