### PR TITLE
fix(ci): Change the parse job in test and update workflows to always use main

### PR DESCRIPTION
**Pull request by RothAndrew**
The Parse job should always be using the action that is in main. This is a bug that got introduced when switching to using a reusable action. Before that change it did always use main, but the change to using a reusable action inadvertently also made it use the action from the PR's branch rather than main. This resulted in [this error](https://github.com/defenseunicorns/delivery-aws-iac/actions/runs/5744514337/job/15570943870#step:3:60)

### CODE REVIEW

**Review by zack-is-cool — APPROVED** [review]
LGTM

**Comment by RothAndrew** [comment]
Actually now that I'm looking at this more, I wonder whether we would like the jobs that use reusable actions to use the branch rather than main? That would likely help us get around one of the headaches with this approach. IMO doing so would not be much of a security risk since only maintainers of the repo with write access can trigger the workflows.

@zack-is-cool thoughts?

**Pull request merged**
