### PR TITLE
Fix bucket ACL error

### LINKED ISSUE #159: Error - cannot create bucket acl
Error: error creating S3 bucket ACL for ex-complete-bastion-72f1-sessionlogs-20230411160015023000000003: AccessControlListNotSupported: The bucket does not allow ACLs
https://github.com/defenseunicorns/iac/actions/runs/4669520528/jobs/8268082680#step:13:7717

### PR DESCRIPTION
**Pull request by zack-is-cool**
closes #159

### CODE REVIEW

**Review by RothAndrew — COMMENTED** [review]
(moving my comment over from the other PR)

Do we want to delete the `depends_on` in the public access block? It got added to try to fix this issue but it obviously didn't work since the issue still happens.

**Comment by zack-is-cool** [comment]
> (moving my comment over from the other PR)
> 
> Do we want to delete the `depends_on` in the public access block? It got added to try to fix this issue but it obviously didn't work since the issue still happens.

Sure. I just made those changes.

**Comment by RothAndrew** [comment]
Got the "empty output" error, rerunning the test

**Comment by zack-is-cool** [comment]
I tried adding a bunch of `depends_on` logic found here to the bastion s3 resource stuff.
https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/master/main.tf

**Review by RothAndrew — APPROVED** [review]

**Pull request merged**
