### PR TITLE
update self-mg-nodegroup defaults to work in GovCloud

### PR DESCRIPTION
**Pull request by ntwkninja**
tuned asg for BB minimum size
updated instance type to an available govcloud dedicate instance type

### CODE REVIEW

**Review by RothAndrew — CHANGES_REQUESTED** [review]
The mixed instances policy should be updated as well. 

https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_InstancesDistribution.html

https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_InstanceRequirements.html

**Comment by ntwkninja** [comment]
> The mixed instances policy should be updated as well.
> 
> https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_InstancesDistribution.html
> 
> https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_InstanceRequirements.html

do we have a mixed instances policy for self_managed_nodegroups? May need to tag up to understand the ask better.

**Review by RothAndrew — APPROVED** [review]

**Pull request merged**
