### PR TITLE
Switch from not-a-build-harness to build-harness

### PR DESCRIPTION
**Pull request by RothAndrew**
Also increase the test timeout to 3 hours and add another retryable error. Previous tests ran into an issue with the EKS cluster taking longer than the 30 minutes that Terraform lets it take, which was causing either a fatal at the 2 hour limit or causing terraform apply to fail. This should fix both of those issues by allowing for a retry and giving the test more time to complete if needed.

### CODE REVIEW

**Comment by RothAndrew** [comment]
Blocked by https://github.com/defenseunicorns/delivery-aws-iac/pull/281

**Review by wirewc — DISMISSED** [review]

**Review by wirewc — APPROVED** [review]

**Review by ntwkninja — APPROVED** [review]
👍

**Pull request merged**
