### PR TITLE
Validate EFS functionality as part of E2E test(s)

### LINKED ISSUE #228: "Access denied" when attempting to create PVC backed by EFS
### Persona

Submitting on behalf of a user who is using this repo to stand up an EKS cluster, and is having problems when trying to use the EFS-backed storageclass

### Description

> I get "access denied" when the provisioner attempts to create a volume

### Use Case

EFS is super important to our users, as it is the easiest way to get reliable (though not particularly performant) PVCs that are cross-AZ and able to be created in Read-Write-Many (RWX) mode.

Our E2E tests that utilize the example root module enables EFS, but doesn't currently verify its functionality.

### Impact

EFS-related functionality will continue to be "non-definitive" since it is a testing gap

### Completion

The E2E test(s) verify that the user is able to provision PVCs backed by EFS. Exact method of that verification is left up to the implementer.

### PR DESCRIPTION
**Pull request by RothAndrew**
Closes #228 

To-Do:
- [x] Create a PVC and job
- [x] Update the golang test code to validate that the job completed successfully -- https://stackoverflow.com/questions/44686568/tell-when-job-is-complete

### CODE REVIEW

**Comment by RothAndrew** [comment]
/test all
(last one was the "insufficient capacity" error 😭

**Comment by RothAndrew** [comment]
/test all
(insufficient capacity again)

**Comment by RothAndrew** [comment]
Ready for review and merge

**Review by ntwkninja — APPROVED** [review]
🚀

**Pull request merged**
